version: 0.2

env:
  variables:
    TF_IN_AUTOMATION: "true"
    TF_ENV: "dev"

phases:
  install:
    commands:
      - curl -fsSL https://releases.hashicorp.com/terraform/1.8.5/terraform_1.8.5_linux_amd64.zip -o tf.zip
      - unzip tf.zip && mv terraform /usr/local/bin/ && rm tf.zip

  pre_build:
    commands:
      - WORKDIR="infra/envs/${TF_ENV}"
      - echo "WORKDIR=${WORKDIR}"
      - cd "${WORKDIR}"
      - echo "PWD: $(pwd)"
      - ls -la
      - terraform init -input=false
      - terraform fmt -check
      - terraform validate

  build:
    commands:
      - WORKDIR="infra/envs/${TF_ENV}"
      - cd "${WORKDIR}"
      - echo "PWD: $(pwd)"
      - ls -la
      - terraform plan -input=false -out plan.out
      - cp plan.out "${CODEBUILD_SRC_DIR}/plan.out"

artifacts:
  files:
    - plan.out
